#
# WARNING: This file is generated by Terraform.  Any direct edits will be overwritten when applying Terraform changes.

-include scripts/base_env.sh

# Define Variables
ifndef project
    override project = $(PROJECT_ID)
endif

ifndef region
    override region = $(LOCATION)
endif


# Default target
.PHONY: all
all: help



# Check the Active GCloud Login
.PHONY: gcloud-check
gcloud-check:
	@echo -n "Active GCP Login: "
	@gcloud config list account --format "value(core.account)"
	@echo -n "Active GCP Project: "
	@gcloud config get-value project 2>&1 | grep -v 'Your active configuration is: '
	@echo -n "Active Service Account: "
	@curl "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email" -H "Metadata-Flavor: Google" && echo ""


# Login and Configure GCloud Project
.PHONY: login
login:
	gcloud auth login --update-adc


# Configure GCloud Project
.PHONY: set-project
set-project:
ifndef project
	$(error project is not set!)
endif
	gcloud config set project $(project)
	gcloud auth application-default set-quota-project $(project)


# Fetch the Metadata Service Account
.PHONY: get-sa
get-sa:
	@curl "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email" -H "Metadata-Flavor: Google" && echo ""


# Update Remote Git Branches
.PHONY: update-branch
update-branch:
	git remote update origin --prune


# Clean Terraform Environment
.PHONY: clean
clean:
	rm -rf infra/.terraform infra/.terraform.lock.hcl infra/.terraform.initialized


# Terraform Init
TERRAFORM_FILES := $(wildcard infra/*.tf)
INIT_TIMESTAMP := infra/.terraform.initialized

$(INIT_TIMESTAMP): $(TERRAFORM_FILES)
	terraform -chdir=infra init
	touch $(INIT_TIMESTAMP)

.PHONY: init
init: $(INIT_TIMESTAMP)

# Terraform Apply
.PHONY: deploy
deploy: init
ifndef project
	$(error project is not set!)
else
	terraform -chdir=infra apply -var="project_id=$(project)"
endif

# Help
.PHONY: help
help:
	@echo "$(service_slug) - $(service_desc)"
	@echo ""
	@echo "Usage:"
	@echo "  make init                 - Initialize Terraform"
	@echo "  make apply                - Apply Terraform changes"
	@echo "  make update-branch        - Refreshes remote Git branches into workspace"
	@echo "  make get-sa               - Fetch the service account associated with the environment"
	@echo "  make gcloud-check         - Check the active GCloud login and project"
	@echo "  make login                - Login to GCloud"
	@echo "  make set-project          - Configure GCloud project"
	@echo "  make clean                - Clean environment"
	@echo "  make help                 - Show help"
